---
title: Swimming analysis of zoea 1 larvae of *Taliepus* *dentatus* reared at different temperatures
subtitle: "Reproducible report"
author: "Lucas Bravo, Milena Cano, Mauricio F. Landaeta, Sergio Navarrete, Simone Baldanzi"
output:
  html_document: 
    keep_md: true
---

This document reproduces and supports all data work and statistical
analysis of the larval swimming in the paper: swimming performance and
morphometrics of the kelp-crab *Taliepus dentatus* zoea 1 exposed to
different rearing temperatures.

```{r message=FALSE, warning=FALSE, echo=TRUE}
knitr::opts_chunk$set(dpi=300)

# Packages used for the analysis
library(tidyverse)
library(lme4)
library(plyr)
library(lmerTest)
library(lme4)
library(car)
library(sjPlot)
library(effects)
library(cowplot)
library(emmeans)
library(sjPlot)
library(multcomp)
```

```{r message=FALSE, warning=FALSE, cache=TRUE, echo=TRUE}
#setting working directory and uploading data (you must set your own working directory)
#data are available in the online version of the article 
setwd("~/Desktop/ECOLAB!/paper tesis/swimming R/NEW TRIAL/")
data<-read.table("copia de full_mean.csv", sep=",", header=TRUE)
```

```{r message=FALSE, warning=FALSE, cache=TRUE, echo=TRUE}
#Tidying data
data1<-data%>%group_by(Temp,Pote,Larva) %>%
  dplyr::summarise(Ist_Vel = mean(IV),
                   Tot_Time= sum(Time), Max_Time=max(Time))%>%rowid_to_column(var='ID')
data1$Temp<-as.factor(data1$Temp)
```

```{r message=FALSE, warning=FALSE, echo=TRUE}
#Calculating median for each response variable
medIV <- ddply(data1, "Temp", summarise, grp.med=median(Ist_Vel))
head(medIV)
medTime <- ddply(data1, "Temp", summarise, grp.med=median(Tot_Time))
head(medTime)
medMax <- ddply(data1, "Temp", summarise, grp.med=median(Max_Time))
head(medMax)
```

```{r message=FALSE, warning=FALSE, echo=TRUE}
#plotting as Kernel Densities
dplot_IV<-ggplot(data1, aes(Ist_Vel, color=Temp))+
  geom_density(kernel = "gaussian")+
  geom_point(aes(x=5.13, y=0),colour="blue",shape=17, size=6)+
  geom_point(aes(x=1.76, y=0),colour="orange",shape=17, size=6)+
  geom_point(aes(x=1.56, y=0),colour="red",shape=17, size=6)+
  theme_classic()+ 
  labs(colour="Temperature", x="Instant Velocity (mm/s)", y="Kernel density")+ 
  scale_x_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.1))) +
  scale_y_continuous(limits = c(0, NA),expand = expansion(mult = c(0, 0.1))) +
  theme(axis.title = element_text(size = 20),axis.text = element_text(size = 20)) +
  scale_colour_manual(values =c("blue","darkorange", "red"))
dplot_IV

dplot_Time<-ggplot(data1, aes(Tot_Time, color=Temp))+
  geom_density(kernel="gaussian")+
  geom_point(aes(x=20.30, y=0),color="blue",shape=17, size=6)+
  geom_point(aes(x=51.20, y=0),color="orange",shape=17, size=6)+
  geom_point(aes(x=54.35, y=0),color="red",shape=17, size=6)+
  theme_classic()+
  labs(colour="Temperature", x="Total Time Swimming (sec)", y="Kernel density")+ 
  scale_x_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.1))) +
  scale_y_continuous(limits = c(0, NA),expand = expansion(mult = c(0, 0.1))) +
  theme(axis.title = element_text(size = 20),axis.text = element_text(size = 20)) +
  scale_color_manual(values =c("blue","darkorange", "red"))
dplot_Time

dplot_Max<-ggplot(data1, aes(Max_Time, color=Temp))+
  geom_density(kernel="gaussian")+
  geom_point(aes(x=10.25, y=0),color="blue",shape=17, size=6)+
  geom_point(aes(x=18.80, y=0),color="orange",shape=17, size=6)+
  geom_point(aes(x=19.25, y=0),color="red",shape=17, size=6)+
  theme_classic()+
  labs(colour="Temperature", x="Total Time Swimming (sec)", y="Kernel density")+ 
  scale_x_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.1))) +
  scale_y_continuous(limits = c(0, NA),expand = expansion(mult = c(0, 0.1))) +
  theme(axis.title = element_text(size = 20),axis.text = element_text(size = 20)) +
  scale_color_manual(values =c("blue","darkorange", "red"))
dplot_Max
```

```{r message=FALSE, warning=FALSE, echo=TRUE}
#Checking for normality
shapiro.test(data1$Ist_Vel)
hist(data1$Ist_Vel)
shapiro.test(data1$Tot_Time)
hist(data1$Tot_Time)

#Checking for heteroscedasticity
leveneTest(data1$Ist_Vel, data1$Temp)
leveneTest(data1$Tot_Time,data1$Temp)

```

```{r echo=TRUE, message=FALSE, warning=FALSE}
#Linear mixed effects model with Log transformed data. 
#Pote is a factor with random effects and larva is nested in Pote 
modIV<-lmer(log(Ist_Vel)~Temp + (Pote|Larva), data=data1)

#model diagnostic
plot(modIV,which = 1)
qqnorm(resid(modIV))
qqline(resid(modIV))

#model output
tab_model(modIV)

#model
modTime<-lmer(log(Tot_Time)~Temp + (Pote|Larva), data=data1)
#model diagnostic
plot(modTime,which = 1)
qqnorm(resid(modTime))
qqline(resid(modTime))

#model output
tab_model(modTime)

```

```{r message=FALSE, warning=FALSE, echo=TRUE}
#pairwise comparison using estimated means
meansIV<-emmeans(modIV, pairwise ~ Temp, adjust="bonferroni")
meansTime<-emmeans(modTime, pairwise ~ Temp, adjust="bonferroni")

#Plotting as boxplots with log transformed data
cld<-cld(meansIV$emmeans,Letters =letters)
data1 <- data1 %>% group_by(Temp) %>%   mutate(cld = case_when(Temp == 12 ~ "b",
                       Temp ==  15 ~ "a",
                       Temp == 17 ~ "a"))

p1<-ggplot(data1, aes(x=Temp, y=log(Ist_Vel), fill=Temp))+geom_boxplot()+
  stat_summary(fun.y =mean,geom="point",width=0.75,
  size=1,linetype="solid") +
  geom_jitter(color="black", size=0.6, alpha=0.3)+
  theme_classic()+labs(x="Temperature", y="IV")+theme(legend.position="none")+
   scale_fill_manual(values =c("blue","darkorange", "red"))+ 
  scale_y_continuous(breaks =c(1,2,0))+ geom_text(x=1.2,y=2.3,label="a",color="red")+
  geom_text(x=1.2,y=2.3,label="a",color="red")+
  geom_text(x=2.2,y=1.3,label="b",color="red")+
  geom_text(x=3.2,y=1.3,label="b",color="red")
p1

p2<-ggplot(data1, aes(x=Temp, y=log(Tot_Time), fill=Temp))+
  geom_boxplot()+ stat_summary(fun.y =mean,geom="point",width=0.75,
  size=1,linetype="solid") + 
  geom_jitter(color="black", size=0.6, alpha=0.3)+
  theme_classic() + theme(legend.position="none") +
  labs(x="Temperature", y="TT")+
   scale_fill_manual(values =c("blue","darkorange", "red"))+
  geom_text(x=1.2,y=4.7,label="a",color="red")+
  geom_text(x=2.2,y=4.7,label="ab",color="red")+
  geom_text(x=3.2,y=4.7,label="b",color="red")
p2

```

```{r message=FALSE, warning=FALSE, echo=TRUE}
#plotting final kernel graphs with insets
plot.with.inset.IV <-
  ggdraw() +
  draw_plot(dplot_IV) +
  draw_plot(p1, x = .49, y = 0.65, width = .3, height = .35)
plot.with.inset.IV

plot.with.inset.Tot_Time <-
  ggdraw() +
  draw_plot(dplot_Time) +
  draw_plot(p2, x = .49, y = 0.65, width = .3, height = .35)
plot.with.inset.Tot_Time

```
